export enum EIConTypes {
  ARROW_UP = 'arrowUp',
  ARROW_DOWN = 'arrowDown',
  ARROW_LEFT = 'arrowLeft',
  ARROW_RIGHT = 'arrowRight',
  MUMBLE = 'mumble',
  CALENDAR = 'calendar',
  CANCEL = 'cancel',
  CHECKMARK = 'checkmark',
  COMMENT_BORDERED = 'commentBordered',
  COMMENT_FILLED = 'commentFilled',
  EDIT = 'edit',
  EYE = 'eye',
  FULL_SCREEN = 'fullScreen',
  HEART_BORDERED = 'heartBordered',
  HEART_FILLED = 'heartFilled',
  LOCATION = 'location',
  LOGOUT = 'logout',
  PROFILE = 'profile',
  REPOST = 'repost',
  SEND = 'send',
  SETTINGS = 'settings',
  SHARE = 'share',
  TIME = 'time',
  UPLOAD = 'upload',
}

export enum EIconColors {
  PINK = 'pink',
  VIOLET = 'violet',
  SLATE = 'slate',
}
